name: Java CI

on: [ push ]

env:
  GITHUB_LOGIN: ${{secrets.GITHUB_LOGIN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  SONAR_URL: ${{secrets.SONAR_URL}}
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}

jobs:
  # This job build, test and stage the artefact and the website for the develop branch
  maven-build-test-site:
    # The tags to select the runner
    runs-on: [ self-hosted, Linux ]
    steps:
      # Environment setup
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6
      # Build and test
      - name: Build and Test with Maven
        run: >
          mvn --batch-mode \
              --update-snapshots \
              --color always \
              --file pom.xml \
              --settings docker/ci-settings.xml \
              -P jacoco \
              verify
      # Check quality with SonarQube
      - name: Quality check with Sonarqube
        ### THIS STEP MUST BE MANUALLY ENABLE AFTER CONFIGURING : SONAR_URL and SONAR_TOKEN secrets.
        if: ${{ false }}
        run: >
          mvn -DskipTests=true \
            -Dsonar.branch.name=$(git rev-parse --abbrev-ref HEAD | tr / _) \
            -Pjacoco,sonar \
            sonar:sonar
      # Stage artifact
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
      # Build and deploy project site
      - name: Build and deploy site with Maven
        if: ${{github.ref == 'refs/heads/develop'}}
        run: >
          mvn --batch-mode \
              --color always \
              --file pom.xml \
              --settings docker/ci-settings.xml \
              site:site site-deploy
