## A simple example to use  GitHub Actions for Java CI with docker and maven
# We build the project using maven.
# Maven can be run in a dedicated docker container
# The credentials are set as env variables and used in a specific ci-settings.xml
# The ENV variables are stored as GitHub Secrets
#
# See https://github.com/ebpro/demomavenarchetype fro details.
name: Java CI

# on every push
on: [push]

# We set env variables for shell, docker and maven.
env:
  GITHUBLOGIN: ${{secrets.GITHUBLOGIN}}
  GITHUBPASSWORD: ${{secrets.GITHUBPASSWORD}}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  SONAR_URL: ${{secrets.SONAR_URL}}
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  MSTEAMS_WEBHOOK: ${{ secrets.MSTEAMS_WEBHOOK }}

jobs:
  # This job build, test, package and deploy the artefact
  maven-build:
    # The tags on the runner
    runs-on: [self-hosted, Linux]
    steps:
      #we get the content of the repository    -
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Build and deploy with Maven and Docker
        uses: ebpro/ci-java-build-action@develop

  # This job runs sonar aga int the build for every branches
  maven-sonar:
    runs-on: [self-hosted, Linux]
    needs: maven-build
    steps:
      - name: Run Sonar
        uses: ebpro/ci-java-sonar-action@develop

  # This job publish the website for develop branch
  maven-site:
    runs-on: [self-hosted, Linux]
    needs: maven-build
    # Develop branch only
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Build and deploy site with Maven
        uses: ebpro/ci-java-site-action@develop
